server:
  port: 8081

spring:
  application:
    name: zuul-cnsl-service
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        prefer-ip-address: true